name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg.exe install imgui[core,dx9-binding,win32-binding]:x64-windows
    
    - name:  Config
      run: echo ::set-env name=DXSDK_DIR::$HOME/cache/
      shell: bash

    - name: Cache
      id:   cache
      uses: actions/cache@v1
      with:
       path: ~/cache
       key:  cache

    - name:  Cache create
      if:    steps.cache.outputs.cache-hit != 'true'
      run:   |
             curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
             7z x _DX2010_.exe DXSDK/Include -o_DX2010_
             7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
             mv _DX2010_/DXSDK $HOME/cache
             rm -fR _DX*_ _DX*_.exe
      shell: bash

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Clean Up
      run: |
        Remove-Item -Recurse -Force vcpkg
